añadi header,logo
PROYECEZE/Segunda-Tarea pull request #1
Opened 2024-07-12 22:48 UTC by PROYECEZE

2024-07-15 14:23 UTC, rhonaldomaster requested changes
@PROYECEZE

<img width="1441" alt="image" src="https://github.com/user-attachments/assets/e3982f1c-3466-4adf-8244-432f4e8331d8">

- No tiene la fuente del texto del diseño
- Faltan elementos como iconos y textos
- El color del fondo no es el correcto
- No esta adaptado para vista móvil

2024-07-15 14:23 UTC, rhonaldomaster commented on .DS_Store
Este archivo no debería estar aquí @PROYECEZE. Genera un .gitignore con el [link que te envié](https://www.toptal.com/developers/gitignore) para que éste archivo (que es del sistema operativo y no aporta al proyecto) no se suba

2024-07-15 14:23 UTC, rhonaldomaster commented on index.css
> +.logo img {
No veo una clase `.logo`, asi que no tiene sentido eso. Mejor colócale la clase a la imagen
```suggestion
.logo {
```

2024-07-15 14:23 UTC, rhonaldomaster commented on index.css
> +.search-bar input {
Es mejor crear una clase que aplicar el estilo al elemento
```suggestion
.search-bar__input {
```

2024-07-15 14:23 UTC, rhonaldomaster commented on index.css
> +.search-bar button {
Es mejor crear una clase que aplicar el estilo al elemento
```suggestion
.search-bar__button {
```

2024-07-15 14:23 UTC, rhonaldomaster commented on index.css
> +.user-options button {
Es mejor crear una clase que aplicar el estilo al elemento
```suggestion
.user-options__button {
```

2024-07-15 14:23 UTC, rhonaldomaster commented on index.html
> +<html>
No quites el idioma a la pagina, es uno de los puntos importantes para hacerla accesible
```suggestion
<html lang="es">
```

2024-07-15 14:23 UTC, rhonaldomaster commented on index.html
> +    <link rel="stylesheet" href="index.css">
Recuerda lo que te mencione anteriormente de crear una carpeta para que no este todo tirado. Si lo haces con `image`, por que no con `css`?

2024-07-15 14:23 UTC, rhonaldomaster commented on image /logo.png
El nombre de la carpeta tiene un espacio 👀

2024-07-15 14:23 UTC, rhonaldomaster commented on index.html
> +    </header>
La tabulación esta rota aqui
```suggestion
  <header>
    <div class="container">
      <div class="logo">
        <img src="image /logo.png">
      </div>
      <div class="search-bar">
        <input type="text" placeholder="¿Qué buscas?">
        <button><i class="fas fa-search"></i></button>
      </div>
      <div class="user-options">
        <button>Todas</button>
        <button>Hola</button>
        <button><i class="fas fa-heart"></i></button>
        <button><i class="fas fa-shopping-cart"></i></button>
      </div>
    </div>
  </header>
```

2024-07-15 14:23 UTC, rhonaldomaster commented on index.html
> +    </body>
```suggestion
</body>
```

2024-07-16 14:43 UTC, rhonaldomaster requested changes
El container del header es diferente al del resto de la pagina, debe ser de 1181 en vez de 1200
<img width="887" alt="image" src="https://github.com/user-attachments/assets/7ea898ab-525d-4f4b-9742-528e99b22425">

Estos textos tienen `line-height` diferente al diseño. Falta colocarle `letter-spacing: 1%;`
<img width="336" alt="image" src="https://github.com/user-attachments/assets/d9a1119a-33bd-421c-a884-89f5ea64d11f">

Al texto rosa como el de `Seleccionar tienda` le falta `line-height` que tiene en el diseño

`header__bottom container` me sale en el diseño que el `padding` es diferente. Lo mediste desde el menu de la izquierda, pero el botón de `sign up` es más alto, por lo que tienes que medirlo desde el botón

Los enlaces de la izquierda no tienen el `line-height` del diseño (18.75px)
<img width="398" alt="image" src="https://github.com/user-attachments/assets/8bf5bea2-614f-4084-ba7d-12d7b18433eb">


Los enlaces de `sign in` y `sign up` no tienen `font-size` o `line-height`

2024-07-16 14:43 UTC, rhonaldomaster commented on css/index.css
> +.header__top-top {
@PROYECEZE no veo una clase `.header`, por lo que es raro que tengas varias clases `.header__`. Puedes modificar el estilo que tienes para `header` para que use la clase `.header` en vez del nombre de la etiqueta

2024-07-16 14:43 UTC, rhonaldomaster commented on css/index.css
> +.header__top {
Esta clase la pondría mas arriba en el archivo. Estas definiendo `header__top-top` antes de `header__top` y se ve algo desordenado así

2024-07-16 14:43 UTC, rhonaldomaster commented on css/index.css
> +.nav__menu {
Igual que el anterior comentario, no veo una clase `.nav`, por lo que esta clase no tiene sentido. Tendría mas sentido algo así, ya que no veo que uses clases del tipo `.nav__` después, sino que usas `.menu__`
```suggestion
.menu {
```

2024-07-16 14:43 UTC, rhonaldomaster commented on css/index.css
> +.header__logo img {
Ya te había mencionado esto anteriormente. Si no tienes un estilo para `.header__logo`, usalo mejor en la imagen
<img width="810" alt="image" src="https://github.com/user-attachments/assets/984a3ac0-e8c0-4733-ae7b-2207956a292f">
```suggestion
.header__logo {
```

2024-07-16 14:43 UTC, rhonaldomaster commented on css/index.css
> +.header__search-bar input {
Igual esto
<img width="802" alt="image" src="https://github.com/user-attachments/assets/1323f83d-16f6-4fad-bffa-764da4e3c44d">
```suggestion
.header__search-input {
```

2024-07-16 14:43 UTC, rhonaldomaster commented on css/index.css
> +.header__search-bar button {
También te había dicho de éste
<img width="796" alt="image" src="https://github.com/user-attachments/assets/133e70ef-b49c-4703-b04b-b9121f117a65">
```suggestion
.header__search-button {
```

2024-07-16 14:43 UTC, rhonaldomaster commented on css/index.css
> +.header__user-options button {
También te había dicho de éste. Además no veo una definición para `.header__user-options`
<img width="798" alt="image" src="https://github.com/user-attachments/assets/5fd452a6-f35b-43aa-88a4-f1a92e202829">
```suggestion
.header__user-options-button {
```

2024-07-16 14:43 UTC, rhonaldomaster commented on css/index.css
> +.header__location img {
Éste es nuevo, pero igual que los otros no veo a los `padres` de las imágenes definidos
```suggestion
.header__hello, 
.header__location {
```

2024-07-16 14:43 UTC, rhonaldomaster commented on css/index.css
> +.nav-links a {
Éste existe, pero queda mas corto usar la clase
```suggestion
.nav-link {
```

2024-07-16 14:43 UTC, rhonaldomaster commented on index.html
>  <html lang="en">
Aquí falta cambiar el idioma, la pagina no está en inglés
```suggestion
<html lang="es">
```

2024-07-16 14:43 UTC, rhonaldomaster commented on index.html
> +          <div class="header__top container">
Esto lo hablamos la otra vez, estás colocando una clase `hijo` por encima del `padre`

2024-07-16 14:43 UTC, rhonaldomaster commented on index.html
> +                </i>
Ese tag `i` no hace nada aquí
```suggestion
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M7 12C9.76142 12 12 9.76142 12 7C12 4.23858 9.76142 2 7 2C4.23858 2 2 4.23858 2 7C2 9.76142 4.23858 12 7 12Z" stroke="#EEEEF7" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                  <path d="M14.0001 14L10.5334 10.5333" stroke="#EEEEF7" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
```

2024-07-16 14:43 UTC, rhonaldomaster commented on index.html
> +                  <a href="#">Seleccionar tienda</a>
Aquí la tabulación hace pensar que `a` esta dentro de `img`
```suggestion
                <a href="#">Seleccionar tienda</a>
```

2024-07-16 14:43 UTC, rhonaldomaster commented on index.html
> +                  <a href="#">Ingresa a tu cuenta</a>
Aquí la tabulación hace pensar que `a` esta dentro de `img`
```suggestion
                <a href="#">Ingresa a tu cuenta</a>
```

2024-07-16 14:43 UTC, rhonaldomaster commented on index.html
> +              </svg>
El corazón y el carrito se supone que son enlaces que te llevan a las paginas de favoritos y carrito de compras

2024-07-16 14:43 UTC, rhonaldomaster commented on css/index.css
> +}
Mejor usa padding para darle anchura
```suggestion
.header__btn {
  padding: 10px 53px;
}
```

2024-07-16 22:06 UTC, rhonaldomaster requested changes

2024-07-16 22:06 UTC, rhonaldomaster commented on css/index.css
> +  font-family: 'Source Sans Pro';
Estas cargando dos fuentes, pero solo se usa la ultima que escribes. Ademas, es buena practica colocar fuentes de backup.
```suggestion
  font-family: 'Source Sans Pro', Arial, sans-serif;
```

2024-07-16 22:06 UTC, rhonaldomaster commented on css/index.css
> +  font-family: "Roboto", sans-serif;
La declaración de arriba `font-family: 'Source Sans Pro';` esta haciendo que esta regla no se use
```suggestion
```

2024-07-16 22:06 UTC, rhonaldomaster commented on css/index.css
> +.header .header__top {
A menos que uses la clase `header__top` fuera de `header`, no necesitas ponerle `header` adelante
```suggestion
.header__top {  
```

2024-07-16 22:06 UTC, rhonaldomaster commented on index.html
> +        </div>
Revisando tu codigo, puedes lograr lo mismo con esto
```suggestion
        <img src="image/logo.png" alt="" class="header__logo">
```

2024-07-16 22:06 UTC, rhonaldomaster commented on index.html
> +          <button class="header__search-button" class="fas fa-search">
Tienes dos declaraciones de clase
```suggestion
          <button class="header__search-button">
```

2024-07-16 22:06 UTC, rhonaldomaster commented on index.html
> +            </a>
No es bueno meter un link dentro de un boton, no tiene sentido
```suggestion
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M7 12C9.76142 12 12 9.76142 12 7C12 4.23858 9.76142 2 7 2C4.23858 2 2 4.23858 2 7C2 9.76142 4.23858 12 7 12Z" stroke="#EEEEF7" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
              <path d="M14.0001 14L10.5334 10.5333" stroke="#EEEEF7" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
```

2024-07-16 22:06 UTC, rhonaldomaster commented on index.html
> +            </div>
Si le agregas `display: block` a `nav-link` puedes omitir meterlo en un div
```suggestion
            <img class="header__location-img" src="image/location.png" alt="location">Todas
            <a class="nav-link" href="#">Seleccionar tienda</a>
```

2024-07-16 22:06 UTC, rhonaldomaster commented on index.html
> +          <a href="" title="Carrito">
Este no es el carrito
```suggestion
          <a href="" title="Favoritos">
```

2024-07-16 22:06 UTC, rhonaldomaster commented on index.html
> +          <a href="" title="Seleccionar">
Este si es el carrito
```suggestion
          <a href="" title="Carrito">
```

2024-07-16 22:06 UTC, rhonaldomaster commented on css/index.css
> +  height: 45px;
No deberias necesitar height si usas las medidas del diseño
```suggestion
  padding: 14px 8px 12px;
  border: none;
  border-radius: 8px 0px 0px 8px;
  width: 468px;
  line-height: 22px;
  font-size: 16px;
```

2024-07-16 22:06 UTC, rhonaldomaster commented on css/index.css
> +  padding: 13px;
Te ayudo un poco aca, con esto deberia verse del mismo alto del input
```suggestion
  padding: 16px 12px;
  line-height: 0;
```

2024-07-16 22:06 UTC, rhonaldomaster commented on css/index.css
> +  font-family: 'Source Sans Pro';
No es necesario aca si ya lo habias declarado en `*`
```suggestion
```

2024-07-16 22:06 UTC, rhonaldomaster commented on css/index.css
> +}
Estos link tienen una fuente diferente en el diseño
```suggestion
.menu__link {
  font-size: 16px;
  font-weight: 400;
  line-height: 18px;
  color: #8794BA;
  font-family: "Roboto", Arial, sans-serif;
}
```

2024-07-17 14:23 UTC, rhonaldomaster requested changes

2024-07-17 14:23 UTC, rhonaldomaster commented on index.html
> +	<title>Mi Tienda Online</title>
Tienes dos títulos
```suggestion
	<title>Mi Tienda Online</title>
```

2024-07-17 14:23 UTC, rhonaldomaster commented on index.html
> +  </body>
Algo que hiciste daño la estructura y quedaron divs cerrados antes de lo que debían
```suggestion
  <header class="header">
    <div class="header__top">
      <div class="header__top-top container">
        <img src="image/logo.png" alt="" class="header__logo">
        <div class="header__search">
          <input class="header__search-input" type="text" placeholder="¿Qué buscas?">
          <button class="header__search-button">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M7 12C9.76142 12 12 9.76142 12 7C12 4.23858 9.76142 2 7 2C4.23858 2 2 4.23858 2 7C2 9.76142 4.23858 12 7 12Z" stroke="#EEEEF7" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              <path d="M14.0001 14L10.5334 10.5333" stroke="#EEEEF7" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </button>
        </div>
        <div class="header__location-hello">
          <div class="header__location">
            <img class="header__location-img" src="image/location.png" alt="location">Todas
            <nav>
              <a class="nav-link" href="#">Seleccionar tienda</a>
            </nav>
          </div>

          <div class="bord"></div>
        
          <div class="header__hello">
            <img class="header__hello-img" src="image/user.png" alt="hello"> Hola!
            <nav>
              <a class="nav-link" href="#">Ingresa a tu cuenta</a>
            </nav>
          </div>
        </div>
          
        <div class="bord"></div> 
        <a href="" title="Favorito">
          <svg width="24" height="21" viewBox="0 0 24 21" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M20.8401 2.60999C19.8086 1.57799 18.4093 0.998169 16.9501 0.998169C15.491 0.998169 14.0916 1.57799 13.0601 2.60999L12.0001 3.66999L10.9401 2.60999C8.79173 0.461607 5.30851 0.461607 3.16012 2.60999C1.01173 4.75838 1.01173 8.24161 3.16012 10.39L4.22012 11.45L12.0001 19.23L19.7801 11.45L20.8401 10.39C21.8721 9.35847 22.4519 7.95913 22.4519 6.49999C22.4519 5.04086 21.8721 3.64152 20.8401 2.60999Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </a>
  
        <div class="bord"></div>
        <a href="" title="Carrito">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M8 23C9.10457 23 10 22.1046 10 21C10 19.8954 9.10457 19 8 19C6.89543 19 6 19.8954 6 21C6 22.1046 6.89543 23 8 23Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path fill-rule="evenodd" clip-rule="evenodd" d="M20 23C21.1046 23 22 22.1046 22 21C22 19.8954 21.1046 19 20 19C18.8954 19 18 19.8954 18 21C18 22.1046 18.8954 23 20 23Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M5.67 6H23L21.32 14.39C21.1313 15.3402 20.2886 16.0186 19.32 16H8.75C7.73948 16.0086 6.88134 15.262 6.75 14.26L5.23 2.74C5.09962 1.7456 4.25291 1.00152 3.25 1H1" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </a>
      </div>
    </div>

    <div class="header__bottom container">
      <div class="header__nav">
        <nav>
          <ul class="menu">
            <li><a class="menu__link text-decoration-none" href="#">Products</a></li>
            <li><a class="menu__link text-decoration-none" href="#">Pricing</a></li>
            <li><a class="menu__link text-decoration-none" href="#">FAQ</a></li>
            <li><a class="menu__link text-decoration-none" href="#">Blog</a></li>
          </ul>
        </nav>
      </div>
      <div class="header__login">
        <a href="#" class="text-decoration-none c-secondary">Sign in</a>
        <a href="#" class="header__btn btn btn--outline">Sign Up</a>
      </div>
    </div>
  </header>
  <main></main>
  <footer></footer>
</body>
```

2024-07-17 15:06 UTC, PROYECEZE commented on index.html
> +            </div>
aqui lo que hice fue esto por eso no me funcionaba 
    <div class="header__location-hello">
                  <img class="header__location-img" src="image/location.png" alt="location">Todas
                    <a class="nav-link" href="#">Seleccionar tienda</a>
             

                <div class="bord"></div>
              
           
                  <img class="header__hello-img" src="image/user.png" alt="hello"> Hola!
                    <a class="nav-link" href="#">Ingresa a tu cuenta</a>
                </div>
               pero ya esta corregido

2024-07-17 21:17 UTC, rhonaldomaster approved these changes

2024-07-17 21:55 UTC, merged